-- J Ranch Risks — full schema bootstrap
-- Generated by concatenating supabase/migrations/*.sql in chronological order.
-- HOW TO USE: open your Supabase project -> SQL Editor -> New query,
-- paste this whole file, and Run. It builds the complete schema on an empty database (no data).
--
BEGIN;

-- ============================================================
-- migration: 20251029115601_remix_batch_4_migrations.sql
-- ============================================================

-- Migration: 20251025154148
-- Create lookup tables first
CREATE TABLE IF NOT EXISTS public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_lines_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.focus_areas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT focus_areas_pkey PRIMARY KEY (id)
);

-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'manager'::text, 'staff'::text])),
  department_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES public.departments(id)
);

-- Create risks table
CREATE TABLE IF NOT EXISTS public.risks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rap_number text NOT NULL UNIQUE,
  department_id uuid,
  company_id uuid,
  service_line_id uuid,
  focus_area_id uuid,
  risk_description text NOT NULL,
  root_cause text,
  action_plan text NOT NULL,
  responsible_person text NOT NULL,
  risk_level text NOT NULL CHECK (risk_level = ANY (ARRAY['1'::text, '2'::text, '3'::text, '4'::text, '5'::text])),
  date_identified date NOT NULL,
  target_completion_date date NOT NULL,
  actual_completion_date date,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'completed'::text, 'overdue'::text])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  priority_level text DEFAULT '3'::text CHECK (priority_level = ANY (ARRAY['1'::text, '2'::text, '3'::text, 'remaining'::text, 'ongoing'::text])),
  CONSTRAINT risks_pkey PRIMARY KEY (id),
  CONSTRAINT risks_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT risks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT risks_service_line_id_fkey FOREIGN KEY (service_line_id) REFERENCES public.service_lines(id),
  CONSTRAINT risks_focus_area_id_fkey FOREIGN KEY (focus_area_id) REFERENCES public.focus_areas(id),
  CONSTRAINT risks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

-- Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  risk_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['overdue'::text, 'due_soon'::text, 'completed'::text])),
  message text NOT NULL,
  read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id)
);

-- Create scorecards table
CREATE TABLE IF NOT EXISTS public.scorecards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  department_id uuid,
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  year integer NOT NULL,
  total_risks integer DEFAULT 0,
  completed_risks integer DEFAULT 0,
  overdue_risks integer DEFAULT 0,
  completion_rate numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scorecards_pkey PRIMARY KEY (id),
  CONSTRAINT scorecards_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);

-- Enable RLS on all tables
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.focus_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scorecards ENABLE ROW LEVEL SECURITY;

-- RLS Policies for lookup tables (read-only for authenticated users)
CREATE POLICY "Authenticated users can view departments" ON public.departments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can view companies" ON public.companies FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can view service_lines" ON public.service_lines FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can view focus_areas" ON public.focus_areas FOR SELECT TO authenticated USING (true);

-- RLS Policies for users table
CREATE POLICY "Users can view all users" ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE TO authenticated USING (auth.uid() = id);

-- RLS Policies for risks table
CREATE POLICY "Users can view all risks" ON public.risks FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can create risks" ON public.risks FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Users can update risks" ON public.risks FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Users can delete risks" ON public.risks FOR DELETE TO authenticated USING (true);

-- RLS Policies for notifications table
CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- RLS Policies for scorecards table
CREATE POLICY "Users can view all scorecards" ON public.scorecards FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can manage scorecards" ON public.scorecards FOR ALL TO authenticated USING (true);

-- Insert initial lookup data
INSERT INTO public.departments (name) VALUES
  ('ADMINISTRATION'),
  ('BILLING'),
  ('CLINICAL SERVICES'),
  ('DIAGNOSTICS'),
  ('DIETARY'),
  ('ENVIRONMENT OF CARE'),
  ('HOUSEKEEPING'),
  ('HUMAN RESOURCES'),
  ('LABORATORY'),
  ('MEDICAL RECORDS'),
  ('NURSING'),
  ('OUTPATIENT SERVICES'),
  ('PHARMACY'),
  ('ACCOUNTING/FINANCE'),
  ('PHYSICIAN/LIP SERVICES'),
  ('QAPI'),
  ('REHABILITATION')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.companies (name) VALUES
  ('ALL'),
  ('ACCESS SERENITY'),
  ('BASTROP'),
  ('BUNKIE'),
  ('DEQUINCY'),
  ('DIVISION'),
  ('FERRIDAY'),
  ('FHC'),
  ('FORENSIC'),
  ('GREENVILLE'),
  ('LAKE CHARLES'),
  ('LEESVILLE'),
  ('MAGNOLIA'),
  ('MINDEN'),
  ('MONROE'),
  ('PLAINVIEW')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.service_lines (name) VALUES
  ('LTAC'),
  ('INPATIENT MEDICAL'),
  ('INPATIENT ADULT'),
  ('INPATIENT GERI'),
  ('INPATIENT ADOL'),
  ('IOP'),
  ('RHC'),
  ('FORENSIC'),
  ('ALL')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.focus_areas (name) VALUES
  ('REVENUE'),
  ('UR/CASH'),
  ('EXPENSE CNTR /PC'),
  ('CLINICAL'),
  ('QUALITY'),
  ('ALL')
ON CONFLICT (name) DO NOTHING;

-- Migration: 20251025154748
-- Drop the old trigger if it exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Create function to insert into users table
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
    'staff'
  );
  RETURN NEW;
END;
$$;

-- Create trigger for new user signups
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Insert the current authenticated user
INSERT INTO public.users (id, email, full_name, role)
SELECT 
  id,
  email,
  COALESCE(raw_user_meta_data->>'full_name', email),
  'admin'
FROM auth.users
WHERE NOT EXISTS (
  SELECT 1 FROM public.users WHERE users.id = auth.users.id
);

-- Migration: 20251025155141
-- Add job_title column to users table
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS job_title text;

-- Remove the foreign key constraint for department_id if it exists
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS fk_users_department;

-- Make department_id nullable (it should already be, but let's ensure it)
ALTER TABLE public.users ALTER COLUMN department_id DROP NOT NULL;

-- Migration: 20251029115032
-- Create an enum for roles
CREATE TYPE public.app_role AS ENUM ('admin', 'staff');

-- Create the user_roles table
CREATE TABLE public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role app_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE (user_id, role)
);

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Create a security definer function to check roles
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;

-- RLS policy: Users can view their own roles
CREATE POLICY "Users can view own roles"
ON public.user_roles
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Migrate existing roles from users table to user_roles table
INSERT INTO public.user_roles (user_id, role)
SELECT id, role::app_role
FROM public.users
ON CONFLICT (user_id, role) DO NOTHING;


-- ============================================================
-- migration: 20251029125824_cfcc0601-1806-428b-af63-131ff26b8190.sql
-- ============================================================
-- Refresh database types by adding a comment
COMMENT ON TABLE public.risks IS 'Risk action plans and tracking';
COMMENT ON TABLE public.users IS 'User profiles and information';
COMMENT ON TABLE public.companies IS 'Company entities';
COMMENT ON TABLE public.departments IS 'Department entities';
COMMENT ON TABLE public.service_lines IS 'Service line entities';
COMMENT ON TABLE public.focus_areas IS 'Focus area entities';
COMMENT ON TABLE public.user_roles IS 'User role assignments';
COMMENT ON TABLE public.notifications IS 'User notifications';
COMMENT ON TABLE public.scorecards IS 'Department scorecards';

-- ============================================================
-- migration: 20251030152605_88b07e71-d2ef-48fa-bc82-8dbba06946bf.sql
-- ============================================================
-- First, let's check and fix the foreign key constraint on risks table
-- The issue is that created_by likely references auth.users, but we should use public.users instead

-- Drop the existing foreign key constraint if it exists
ALTER TABLE public.risks 
DROP CONSTRAINT IF EXISTS risks_created_by_fkey;

-- Add the foreign key constraint to reference public.users
ALTER TABLE public.risks
ADD CONSTRAINT risks_created_by_fkey 
FOREIGN KEY (created_by) 
REFERENCES public.users(id) 
ON DELETE SET NULL;

-- Create the trigger to handle new user signups (if not exists)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- migration: 20251030153059_561cadb7-25db-4df0-90a7-89f2f350da52.sql
-- ============================================================
-- 1) Align public.users IDs to auth.users IDs for accounts with same email
WITH matches AS (
  SELECT pu.id AS old_id, au.id AS new_id
  FROM public.users pu
  JOIN auth.users au ON au.email = pu.email
  WHERE pu.id <> au.id
)
UPDATE public.users pu
SET id = m.new_id
FROM matches m
WHERE pu.id = m.old_id;

-- 2) Backfill any remaining missing users from auth.users after alignment
INSERT INTO public.users (id, email, full_name, role)
SELECT au.id,
       au.email,
       COALESCE(au.raw_user_meta_data->>'full_name', au.email),
       'staff'
FROM auth.users au
LEFT JOIN public.users pu ON pu.id = au.id
WHERE pu.id IS NULL;

-- ============================================================
-- migration: 20251030164931_689a0f22-d028-4f2e-bad2-d958c18e223a.sql
-- ============================================================
-- Add company_id to users table for facility assignment
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS company_id uuid REFERENCES public.companies(id);

-- Update RLS policy on risks to only allow users to update their own risks
DROP POLICY IF EXISTS "Users can update risks" ON public.risks;

CREATE POLICY "Users can update own risks"
ON public.risks
FOR UPDATE
USING (auth.uid() = created_by);

-- ============================================================
-- migration: 20251103145753_329523f5-cf15-424b-8590-23ca9b67fbde.sql
-- ============================================================
-- First, we need to handle the transition from text to uuid for responsible_person
-- Add a new column for responsible_person_id
ALTER TABLE public.risks ADD COLUMN responsible_person_id uuid REFERENCES public.users(id);

-- Note: Existing data in responsible_person (text) cannot be automatically converted
-- You may need to manually map names to user IDs if there's existing data

-- For now, we'll keep both columns temporarily to allow for data migration
-- After data is migrated, you can drop the old responsible_person column with:
-- ALTER TABLE public.risks DROP COLUMN responsible_person;
-- ALTER TABLE public.risks RENAME COLUMN responsible_person_id TO responsible_person;

-- Update the RLS policy to allow both creator and responsible person to update
DROP POLICY IF EXISTS "Users can update own risks" ON public.risks;

CREATE POLICY "Users can update own or assigned risks" 
ON public.risks 
FOR UPDATE 
USING (
  auth.uid() = created_by OR 
  auth.uid() = responsible_person_id
);

-- ============================================================
-- migration: 20251103151117_f25ae2d3-4209-482c-9cb1-4edd174435be.sql
-- ============================================================
-- Add priority_status column to risks table
ALTER TABLE public.risks ADD COLUMN priority_status text;

-- ============================================================
-- migration: 20251103161549_0e50aae5-771a-4bd6-97dd-18abf8e005b7.sql
-- ============================================================
-- Drop the policy first
DROP POLICY IF EXISTS "Users can update own or assigned risks" ON public.risks;

-- Drop the foreign key constraint
ALTER TABLE public.risks DROP CONSTRAINT IF EXISTS risks_responsible_person_id_fkey;

-- Change responsible_person_id to array of UUIDs to support multiple responsible parties
ALTER TABLE public.risks 
  ALTER COLUMN responsible_person_id TYPE uuid[] USING ARRAY[responsible_person_id],
  ALTER COLUMN responsible_person_id SET DEFAULT '{}';

-- Recreate the policy to check if user is in the array of responsible persons
CREATE POLICY "Users can update own or assigned risks" 
ON public.risks 
FOR UPDATE 
USING ((auth.uid() = created_by) OR (auth.uid() = ANY(responsible_person_id)));

-- ============================================================
-- migration: 20251103163247_0d2b21d0-f6d3-4668-93e7-a087fdf11588.sql
-- ============================================================
-- Create a function to check if a user is an admin (security definer to avoid RLS recursion)
CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE id = user_id
    AND role = 'admin'
  );
$$;

-- Drop the existing update policy
DROP POLICY IF EXISTS "Users can update own profile" ON public.users;

-- Create new update policy that allows users to update their own profile OR admins to update any profile
CREATE POLICY "Users can update own profile or admins can update any"
ON public.users
FOR UPDATE
USING (auth.uid() = id OR public.is_admin(auth.uid()));

-- ============================================================
-- migration: 20260130193705_21ccfc2e-4d48-4fbb-8c53-637b84488ff8.sql
-- ============================================================
-- Add completion_percentage column to risks table
ALTER TABLE public.risks
ADD COLUMN completion_percentage integer DEFAULT 0;

-- ============================================================
-- migration: 20260203181609_5316b2ad-f4a9-42bf-ad92-f7a681a9e5b4.sql
-- ============================================================
-- Drop the restrictive update policy
DROP POLICY IF EXISTS "Users can update own or assigned risks" ON public.risks;

-- Create a new policy that allows all authenticated users to update risks
CREATE POLICY "Authenticated users can update risks" 
ON public.risks 
FOR UPDATE 
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

-- ============================================================
-- migration: 20260203200133_152d8d9c-f001-44ec-9f9a-439b45adbf3e.sql
-- ============================================================
-- Drop the existing delete policy
DROP POLICY IF EXISTS "Users can delete risks" ON public.risks;

-- Create a new policy that allows only admins to delete risks
CREATE POLICY "Admins can delete risks" 
ON public.risks 
FOR DELETE 
USING (is_admin(auth.uid()));

-- ============================================================
-- migration: 20260206162526_c9e55f25-0195-4c54-8f16-3f1ea43ee48a.sql
-- ============================================================
-- Step 1: Assign all users without a facility to Lake Charles
UPDATE public.users 
SET company_id = 'e40784c0-1653-4d14-a6c3-455045a071c7'
WHERE company_id IS NULL;

-- Step 2: Create CORPORATE facility
INSERT INTO public.companies (name) VALUES ('CORPORATE');

-- Step 3: Create facility_access hierarchy table
CREATE TABLE public.facility_access (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  child_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(parent_id, child_id),
  CHECK (parent_id != child_id)
);

-- Enable RLS on facility_access
ALTER TABLE public.facility_access ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view facility hierarchy
CREATE POLICY "Authenticated users can view facility hierarchy"
ON public.facility_access
FOR SELECT
USING (true);

-- Step 4: Insert hierarchy record (Corporate -> Lake Charles)
-- Corporate can access Lake Charles data
INSERT INTO public.facility_access (parent_id, child_id)
SELECT 
  (SELECT id FROM public.companies WHERE name = 'CORPORATE'),
  'e40784c0-1653-4d14-a6c3-455045a071c7';

-- Step 5: Create security definer function to check facility access
CREATE OR REPLACE FUNCTION public.can_access_facility(_user_id uuid, _target_facility_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    -- User has no facility restriction (null target = allow)
    _target_facility_id IS NULL
    OR
    -- User belongs to the same facility
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = _user_id 
      AND company_id = _target_facility_id
    )
    OR
    -- User's facility is a parent of the target facility
    EXISTS (
      SELECT 1 FROM facility_access fa
      JOIN users u ON u.company_id = fa.parent_id
      WHERE u.id = _user_id
      AND fa.child_id = _target_facility_id
    )
    OR
    -- User is in the parent facility itself (can see their own data)
    EXISTS (
      SELECT 1 FROM users u
      JOIN facility_access fa ON fa.parent_id = u.company_id
      WHERE u.id = _user_id
      AND fa.parent_id = _target_facility_id
    )
$$;

-- Step 6: Update RLS policies for risks table
-- Drop existing SELECT policy
DROP POLICY IF EXISTS "Users can view all risks" ON public.risks;

-- Create new facility-based SELECT policy
CREATE POLICY "Users can view facility risks"
ON public.risks
FOR SELECT
USING (
  can_access_facility(auth.uid(), company_id)
);

-- Step 7: Update RLS policies for users table
-- Drop existing SELECT policy
DROP POLICY IF EXISTS "Users can view all users" ON public.users;

-- Create new facility-based SELECT policy for users
CREATE POLICY "Users can view facility users"
ON public.users
FOR SELECT
USING (
  can_access_facility(auth.uid(), company_id)
);

-- ============================================================
-- migration: 20260206163007_e3e9a57a-2a58-4d7c-b9b4-875cb32070b1.sql
-- ============================================================
-- Fix: Allow admins to update any user regardless of facility access
-- Drop the existing update policy
DROP POLICY IF EXISTS "Users can update own profile or admins can update any" ON public.users;

-- Recreate with proper WITH CHECK for admins
CREATE POLICY "Users can update own profile or admins can update any"
ON public.users
FOR UPDATE
USING (
  (auth.uid() = id) OR is_admin(auth.uid())
)
WITH CHECK (
  (auth.uid() = id) OR is_admin(auth.uid())
);

-- ============================================================
-- migration: 20260206163526_7cbc7500-8000-4e80-89a8-96f9ad11677b.sql
-- ============================================================
-- Fix: Allow admins to view all users regardless of facility
-- This is needed for user management in the admin panel

-- Drop the existing SELECT policy
DROP POLICY IF EXISTS "Users can view facility users" ON public.users;

-- Recreate with admin bypass
CREATE POLICY "Users can view facility users or admins view all"
ON public.users
FOR SELECT
USING (
  is_admin(auth.uid()) OR can_access_facility(auth.uid(), company_id)
);

-- ============================================================
-- migration: 20260206164050_421536ff-0895-46de-8aca-325824b6f635.sql
-- ============================================================
-- Update RLS policy for risks to also show risks where user is assigned
-- A risk should be visible if:
-- 1. User can access the risk's facility, OR
-- 2. User is assigned to the risk (in responsible_person_id array)

DROP POLICY IF EXISTS "Users can view facility risks" ON public.risks;

CREATE POLICY "Users can view facility or assigned risks"
ON public.risks
FOR SELECT
USING (
  can_access_facility(auth.uid(), company_id)
  OR auth.uid() = ANY(responsible_person_id)
);

-- ============================================================
-- migration: 20260220151826_baa63daf-c4c1-487c-9d66-dc5df0264df2.sql
-- ============================================================
ALTER TABLE public.risks ADD COLUMN IF NOT EXISTS ongoing_risk boolean NOT NULL DEFAULT false;

-- ============================================================
-- migration: 20260220153944_2e6f2553-fc33-44fb-b797-3aaf8fa6dd84.sql
-- ============================================================
ALTER TABLE public.risks DROP CONSTRAINT IF EXISTS risks_priority_level_check;

-- ============================================================
-- migration: 20260323180904_8d880c92-30b1-43d1-890a-52805a4713d1.sql
-- ============================================================
CREATE POLICY "Admins can delete users"
ON public.users
FOR DELETE
TO authenticated
USING (is_admin(auth.uid()));

-- ============================================================
-- migration: 20260323185012_a2ac545e-1c24-42e0-908a-3976c181ddbc.sql
-- ============================================================
INSERT INTO facility_access (parent_id, child_id) VALUES ('40ef8132-b9f6-4f88-ab5e-ac6e1bf6bc14', '72402282-b86c-497f-9e87-cbe75dfeccc1');

-- ============================================================
-- migration: 20260323203705_4a888491-ea9f-44f3-9b48-9c4f64fcd20a.sql
-- ============================================================

DROP POLICY IF EXISTS "Users can view facility users or admins view all" ON public.users;

CREATE POLICY "Users can view facility users or admins view all"
ON public.users FOR SELECT
TO public
USING (
  is_admin(auth.uid())
  OR can_access_facility(auth.uid(), company_id)
  OR EXISTS (
    SELECT 1 FROM facility_access fa
    JOIN users u ON u.company_id = fa.child_id
    WHERE u.id = auth.uid()
    AND fa.parent_id = users.company_id
  )
);


-- ============================================================
-- migration: 20260323204246_24ee844f-e543-4d68-b1d8-74de62f89d40.sql
-- ============================================================
-- Create a security definer function to check if user's facility 
-- is a child of a target parent facility
CREATE OR REPLACE FUNCTION public.user_facility_is_child_of(_user_id uuid, _parent_facility_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM facility_access fa
    JOIN users u ON u.company_id = fa.child_id
    WHERE u.id = _user_id
    AND fa.parent_id = _parent_facility_id
  )
$$;

-- Recreate the policy using the function
DROP POLICY IF EXISTS "Users can view facility users or admins view all" ON public.users;

CREATE POLICY "Users can view facility users or admins view all"
ON public.users FOR SELECT
TO public
USING (
  is_admin(auth.uid())
  OR can_access_facility(auth.uid(), company_id)
  OR user_facility_is_child_of(auth.uid(), company_id)
);

-- ============================================================
-- migration: 20260408143509_bc1c332a-1a2b-45a9-a8bc-44f4b632acca.sql
-- ============================================================
ALTER TABLE public.risks ADD COLUMN sector text NULL;

-- ============================================================
-- migration: 20260408151507_94814945-b400-4580-aceb-2e2cb90ff617.sql
-- ============================================================
ALTER TABLE public.risks ADD COLUMN risk_origin text NULL;

-- ============================================================
-- migration: 20260420173630_d6f45295-9f25-4f7d-be1b-45859d35b407.sql
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS risks_rap_number_unique_idx ON public.risks (rap_number);

-- ============================================================
-- migration: 20260421164818_812e25d2-04bc-4b14-bb46-be1b4bb1be0e.sql
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_executive_viewer(_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT _user_id IN (
    '959f6dbd-f739-4f64-88c1-b60a6deee3fd'::uuid,
    '0a3b32b0-c8c5-4998-aa13-e485f8bbc44f'::uuid
  );
$$;

DROP POLICY IF EXISTS "Users can view facility or assigned risks" ON public.risks;

CREATE POLICY "Users can view facility or assigned risks"
ON public.risks
FOR SELECT
USING (
  can_access_facility(auth.uid(), company_id)
  OR auth.uid() = ANY (responsible_person_id)
  OR public.is_executive_viewer(auth.uid())
);


-- ============================================================
-- migration: 20260421195326_67eb11c2-be42-4d6c-ad9c-e94219c38367.sql
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_risks_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_risks_updated_at ON public.risks;

CREATE TRIGGER set_risks_updated_at
BEFORE UPDATE ON public.risks
FOR EACH ROW
EXECUTE FUNCTION public.set_risks_updated_at();

-- ============================================================
-- migration: 20260518150934_1ee76cd8-62c3-415b-b77d-a7658c096b62.sql
-- ============================================================

-- 1. Add visibility column
ALTER TABLE public.risks
ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'facility_only';

ALTER TABLE public.risks
ADD CONSTRAINT risks_visibility_check
CHECK (visibility IN ('corporate_only', 'facility_only', 'both'));

-- 2. Helper SECURITY DEFINER function: is the user's facility a parent of the target facility?
CREATE OR REPLACE FUNCTION public.user_is_corporate_parent_of(_user_id uuid, _target_facility_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM facility_access fa
    JOIN users u ON u.company_id = fa.parent_id
    WHERE u.id = _user_id
    AND fa.child_id = _target_facility_id
  )
  OR EXISTS (
    -- user is in the parent facility itself, targeting their own facility
    SELECT 1 FROM users u
    JOIN facility_access fa ON fa.parent_id = u.company_id
    WHERE u.id = _user_id
    AND u.company_id = _target_facility_id
  );
$$;

-- 3. Replace SELECT policy on risks to honor visibility
DROP POLICY IF EXISTS "Users can view facility or assigned risks" ON public.risks;

CREATE POLICY "Users can view facility or assigned risks"
ON public.risks
FOR SELECT
USING (
  -- Admins and executive viewers always see everything
  is_admin(auth.uid())
  OR is_executive_viewer(auth.uid())
  -- Creator always sees their own risks
  OR auth.uid() = created_by
  -- Anyone assigned as responsible can see it
  OR (auth.uid() = ANY (responsible_person_id))
  OR (
    CASE
      WHEN visibility = 'corporate_only' THEN
        -- Only Corporate (parent-facility) users can see
        user_is_corporate_parent_of(auth.uid(), company_id)
      ELSE
        -- facility_only or both: normal facility access
        can_access_facility(auth.uid(), company_id)
    END
  )
);


-- ============================================================
-- migration: 20260520193455_cb0ec27c-fa51-4bc4-9318-d44d92f719ac.sql
-- ============================================================
UPDATE risks SET created_at = '2026-05-13 12:00:00+00' WHERE rap_number = 'RAP-1779293673441';
UPDATE risks SET created_at = '2026-05-13 12:01:00+00' WHERE rap_number = 'RAP-1779293983285';
UPDATE risks SET created_at = '2026-05-13 12:02:00+00' WHERE rap_number = 'RAP-1779294152687';

COMMIT;
