-- Clean slate: original seeded a facility_access hierarchy row using company
-- UUIDs specific to the freedomrap database. Those IDs do not exist in a fresh
-- database, so the row is intentionally omitted. Configure facility hierarchy
-- for your own companies after setup.
-- Original statement (kept for reference):
-- INSERT INTO facility_access (parent_id, child_id) VALUES ('40ef8132-b9f6-4f88-ab5e-ac6e1bf6bc14', '72402282-b86c-497f-9e87-cbe75dfeccc1');
